### ISSUE TITLE
getObject fails with Status {statusCode = 301, statusMessage = "Moved Permanently"}

### ISSUE THREAD

**Issue by joeyh** [aristidb/aws#160]
This is a forwarded bug report from 
http://git-annex.branchable.com/bugs/Can__39__t_get_content_from_S3_with_s3-aws_library/ 

String to sign: "GET\n\n\nThu, 23 Apr 2015 18:52:33 GMT\n/BUCKET/GPGHMACSHA1--417830f4c50a2887674917abd2c18c522853255a"
Host: "BUCKET.s3-ap-southeast-1.amazonaws.com"
Path: "/GPGHMACSHA1--417830f4c50a2887674917abd2c18c522853255a"
Query string: ""
Response status: Status {statusCode = 301, statusMessage = "Moved Permanently"}
Response header 'x-amz-request-id': '9AEC998DAE32A80F'
Response header 'x-amz-id-2': 'ItIm3aA92UrLJzPQhUy3WLIkP8ld4Kk2yzJxph89UdDFAq5itGuNLpO1/Xy5AbW/eXxgvWLsMcQ='
Response header 'Content-Type': 'application/xml'
Response header 'Transfer-Encoding': 'chunked'
Response header 'Date': 'Thu, 23 Apr 2015 18:52:34 GMT'
Response header 'Server': 'AmazonS3'
Response metadata: S3: request ID=9AEC998DAE32A80F, x-amz-id-2=ItIm3aA92UrLJzPQhUy3WLIkP8ld4Kk2yzJxph89UdDFAq5itGuNLpO1/Xy5AbW/eXxgvWLsMcQ=
GetObject: HeaderException {headerErrorMessage = "ETag missing"}

I have managed to reproduce this problem using a modified version of Examples/GetObject.hs, and some credentials the user gave me to access the bucket that causes this problem.

This bucket does contain the file we're trying to request here. An older version of git-annex used the "S3" library to put it there, and that old version can still get it out.

I don't know why S3 would be redirecting in this case, but it seems that the redirect needs to be followed in this case, and that would probably fix it. AFAIK the default http-client manager does follow redirects, so why didn't it follow here I wonder?

The owner of this bucket may be willing to give you creds to access it, or I have them if you want me to try something to debug further.

**Comment by joeyh** [comment]
This is looking likely to have been user error. I'll close the bug if that turns out to have been the case, or follow up again if not.

**Comment by aristidb** [comment]
Alright, I'll wait for your update.

Joey Hess <notifications@github.com> schrieb am Do., 23. Apr. 2015 um
21:09 Uhr:

**Comment by joeyh** [comment]
So I do think there's some infelicity with the aws library here.

If I create a bucket using hS3, with location set to ap-southeast-2,
I cannot get files from it using aws. I get the redirection message
mentioned before.

When I use the s3cmd interface to look at that bucket, I also see
evidence of some kind of redirection:

joey@darkstar:~>s3cmd info s3://s3-43302240-076c-4420-8099-f2ef0b517e5f
s3://s3-43302240-076c-4420-8099-f2ef0b517e5f/ (bucket):
   Location:  ap-southeast-2
WARNING: Redirected to: s3-43302240-076c-4420-8099-f2ef0b517e5f.s3-ap-southeast-2.amazonaws.com
   Expiration Rule: none
   policy: none
   ACL:       joeyhess: FULL_CONTROL

Hmm, when I look at this bucket in the AWS web panel, it says it's in Sydney;
other buckets I've created in ap-southeast-2 using the aws library are in
Singapore. Perhaps that's why the redirect.

So, hS3 seems to be doing something that introduces this redirection for some
reason, and the aws library doesn't handle it, while other S3 stuff like s3cmd
does. So this does seem to be a problem with this library (perhaps also
with hS3 for doing whatever it is that causes this redirection to be needed).

I've set the above bucket to public access, so feel free to use it for testing
this.

-- 
see shy jo

**Comment by aristidb** [comment]
I pushed a potential fix to master but was too lazy to actually test it for
now. Could you see if it fixes your issue?

Joey Hess <notifications@github.com> schrieb am Sa., 25. Apr. 2015 um
03:36 Uhr:

**Comment by joeyh** [comment]
Interestingly, the bucket that had been redirecting no longer seems to
be, so I can't test the fixed aws. And I've been having trouble reproducing
the problem again.

-- 
s.ee shy jo

**Comment by joeyh** [comment]
Well, it seems the change in master didn't fix it:

[2015-04-27 18:04:49 JEST] String to sign: "GET\n\n\nMon, 27 Apr 2015 22:04:49 GMT\n/s3-43302240-076c-4420-8099-f2ef0b517e5f/SHA256E-s3--98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4"
[2015-04-27 18:04:49 JEST] Host: "s3-43302240-076c-4420-8099-f2ef0b517e5f.s3-ap-southeast-1.amazonaws.com"
[2015-04-27 18:04:49 JEST] Path: "/SHA256E-s3--98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4"
[2015-04-27 18:04:49 JEST] Query string: ""
[2015-04-27 18:04:52 JEST] Response status: Status {statusCode = 301, statusMessage = "Moved Permanently"}
[2015-04-27 18:04:52 JEST] Response header 'x-amz-request-id': '24039E23C74EB8F3'
[2015-04-27 18:04:52 JEST] Response header 'x-amz-id-2': 'YjMafBdkR97aAfLRz2TFR+jNLBY5a8S+NYP+V+SwQtZlVkYCvshfQRJbZPONPJ8I5GLsHw18pWs='
[2015-04-27 18:04:52 JEST] Response header 'Content-Type': 'application/xml'
[2015-04-27 18:04:52 JEST] Response header 'Transfer-Encoding': 'chunked'
[2015-04-27 18:04:52 JEST] Response header 'Date': 'Mon, 27 Apr 2015 22:04:51 GMT'
[2015-04-27 18:04:52 JEST] Response header 'Server': 'AmazonS3'
[2015-04-27 18:04:52 JEST] Response metadata: S3: request ID=24039E23C74EB8F3, x-amz-id-2=YjMafBdkR97aAfLRz2TFR+jNLBY5a8S+NYP+V+SwQtZlVkYCvshfQRJbZPONPJ8I5GLsHw18pWs=

This is after misconfiguring it to use ap-southeast-1 instead of
ap-southeast-2. hS3 successfully follows the redirect in this situation.

-- 
see shy jo

**Comment by aristidb** [comment]
I don't see the Location header? *confused*

Joey Hess <notifications@github.com> schrieb am Di., 28. Apr. 2015 00:09:

**Comment by aristidb** [comment]
OK, I can reproduce with

```
simpleAws cfg ((defServiceConfig :: S3.S3Configuration NormalQuery) { S3.s3Endpoint = S3.s3EndpointApSouthEast }) (S3.getBucket "s3-43302240-076c-4420-8099-f2ef0b517e5f")
```

Now to figure out what causes the issue.

**Comment by aristidb** [comment]
LOL, Amazon puts the new location in the XML, not in the Location header as HTTP applications would.

**Comment by aristidb** [comment]
Now you get this error:

```
S3Error {s3StatusCode = Status {statusCode = 301, statusMessage = "Moved Permanently"}, s3ErrorCode = "PermanentRedirect", s3ErrorMessage = "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.", s3ErrorResource = Nothing, s3ErrorHostId = Just "0nMLIW07EFkNM2qPz/PqolsD3A25EtB3SsdcNVT4XwEVBI2khZBBHAuCzq5VAVrIxt93lMUOH2U=", s3ErrorAccessKeyId = Nothing, s3ErrorStringToSign = Nothing}
```

That's already better, I guess. I'm reluctant to automatically handle this as a redirect in the S3 core, as people should specify the correct endpoint, but I'm open to exposing the correct endpoint in the S3Error.

**Comment by aristidb** [comment]
Alright, now the error type will contain this field:

```
s3ErrorEndpoint = Just "s3-ap-southeast-2.amazonaws.com"
```

This way, the application can decide to deal with the situation if necessary.

**Comment by joeyh** [comment]
Aristid Breitkreuz wrote:
> That's already better, I guess. I'm reluctant to automatically handle this as a
> redirect in the S3 core, as people should specify the correct endpoint, but I'm
> open to exposing the correct endpoint in the S3Error.

I'm almost positive I've seen this happen to a bucket where the correct
endpoint was specified. As if, perhaps, it got redirected to a different
endpoint when the bucket was created due to capacity issues..

If that's the case, it seems that aws it should follow the redirect
automatically. What's the downside to aws following it?

-- 
see shy jo

**Comment by aristidb** [comment]
The downside is performance. If you have a test case where you specify the correct endpoint yet get this error, we can revisit this decision.

If you disagree with my decision, it is now also possible (as I expose the endpoint response field) to write yourself a wrapper function that does what you want.
